icons = "awesome"

[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = "|"
separator_fg = "#aaaaaa"
separator_bg = "#282828"

[[block]]
block = "weather"
# format = "{weather} and {apparent}째 in {location}"
format = "{apparent}째 {weather}"
# autolocate = true
[block.service]
name = "openweathermap"
api_key = "26e1b521f7083d19b7eefe9b92961288"
units = "imperial"
place = "Austin"

[[block]]
block = "uptime"

[[block]]
block = "net"
interval = 3
# format_alt = "{ip}"

[[block]]
block = "disk_space"
format = "{icon} {available} {unit} free"

[[block]]
block = "pacman"
interval = 86400
format = "{both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "linux"
aur_command = "yay -Qua"

[[block]]
block = "nvidia_gpu"
show_memory = false
show_fan_speed=true
interval = 3

[[block]]
block = "memory"
format_mem = "{Mupi}%"
format_swap = "{SUpi}%"

[[block]]
block = "cpu"
format = "{utilization} {frequency}"
interval = 3

[[block]]
block = "temperature"
interval = 3
idle = 60
info = 70
# chip = "k10temp-pci-00c3"
collapsed = false
format = "{average}째C, {max}째C max"

[[block]]
block = "sound"
step_width = 1
on_click = "killall pavucontrol || pavucontrol &"

[[block]]
block = "time"
format = "%-I:%M%P"
interval = 60
on_click = "notify-send $(date +%D)"
