icons = "awesome"

[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = "|"
separator_fg = "#aaaaaa"
separator_bg = "#282828"

[[block]]
block = "music"
player = "mpd"
buttons = ["prev", "play", "next"]
# max_width = 35

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "memory"
format_mem = "{Mupi}%"
format_swap = "{SUpi}%"
warning_mem = 60
warning_swap = 25
critical_mem = 80
critical_swap = 75

[[block]]
block = "cpu"

[[block]]
block = "battery"

[[block]]
block = "temperature"
interval = 5
format = "{max}° max, {average}° avg"

[[block]]
block = "toggle"
text = ""
command_state = "true"
command_on = "notify-send DUNST_COMMAND_PAUSE"
command_off = "notify-send DUNST_COMMAND_RESUME"

[[block]]
block = "backlight"
step_width = 1

[[block]]
block = "sound"
step_width = 1
on_click = "/home/joseph/config/scripts/bar/volume.sh"

[[block]]
block = "time"
format = "%-I:%M%P"
interval = 60
on_click = "/home/joseph/config/scripts/bar/date.sh"
