[icons]
icons = "awesome5"
[icons.overrides]
volume_muted = "\uf466" # TODO: remove once nerdfont stops clobbering awesome
cpu = "\uf0e4"
update = "📦"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = "|"
separator_fg = "#aaaaaa"
separator_bg = "#282828"

[[block]]
block = "weather"
format = " $icon {$temp}F "
autolocate = true
service = { name = "openweathermap", units = "imperial", place = "Sunnyvale" }

[[block]]
block = "pacman"
interval = 86400
format = " $icon $both "
critical_updates_regex = "linux"
aur_command = "paru -Qua"
theme_overrides = { "info_bg" = "#282828" }

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon_swap $swap_used_percents "

[[block]]
block = "cpu"
format = " $icon $utilization "
interval = 3

[[block]]
block = "temperature"
interval = 3
idle = 50
info = 70
format = " $icon {$average}C "
chip = "k10temp-pci-*"
inputs = ["Tccd1"]

[[block]]
block = "notify"

[[block]]
block = "sound"
step_width = 1
click = [{ cmd = "killall pavucontrol || pavucontrol &", button = "left" }]

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%-I:%M%P') "
interval = 3
click = [{ button = "left", cmd = "notify-send $(date +%D)" }]
