icons = "awesome"

[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = "|"
separator_fg = "#aaaaaa"
separator_bg = "#282828"

[[block]]
block = "weather"
format = "{apparent}"
autolocate = true
service = { name = "openweathermap", units = "imperial", place = "Sunnyvale" }

[[block]]
block = "apt"
interval = 1800
icons_format = " 📦 "
format = "{count:1}"
format_singular = "{count:1}"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
# shows dmenu with cached available updates. Any dmenu alternative should also work.
on_click = "APT_CONFIG=/tmp/i3rs-apt/apt.conf apt list --upgradable | tail -n +2 | rofi -dmenu"

# [[block]]
# block = "backlight"
# step_width = 1
# invert_icons = true
# 
# [[block]]
# block = "battery"
# driver = "upower"

[[block]]
block = "notify"

[[block]]
block = "sound"
step_width = 1
on_click = "killall pavucontrol || pavucontrol &"

[[block]]
block = "time"
icons_format = " "
format = "%-I:%M%P"
interval = 60
on_click = "notify-send $(date +%D)"
