[registries.crates-io]
protocol = "sparse"

[build]
rustflags = ["-Z", "threads=8"]
target-dir = ".cargo/build"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# [unstable]
# codegen-backend = true
#
# [profile.dev]
# codegen-backend = "cranelift"
