invert_scrolling = false
error_format = " "

[icons]
icons = "awesome6"
[icons.overrides]
volume_muted = ""
cpu = ""
cpu_boost_on = "󱐋"
backlight = ["󰌶", "󱩎", "󱩏", "󱩐", "󱩑", "󱩒", "󱩓", "󱩔", "󱩕", "󱩖", "󰛨"]
weather_clouds_night = ""

[theme]
theme = "ctp-mocha"
[theme.overrides]
separator = "|"
separator_fg = "#cdd6f4"
separator_bg = "#313244"

[[block]]
block = "music"
icons_format = " {icon} "
format = " $icon {$combo.str(max_w:35) $prev$play$next |}"

[[block]]
block = "weather"
format = " $icon $temp "
format_alt = " $icon $temp {({$temp_fmin}-{$temp_fmax}) |}"
autolocate = true
autolocate_interval = "once"
service = { name = "openweathermap", units = "imperial", forecast_hours = 24 }

[[block]]
block = "memory"
format = " $icon $mem_used_percents.bar(v:true) "
format_alt = " $icon_swap $swap_used_percents.bar(v:true) "

[[block]]
block = "cpu"
format = " $icon $utilization.bar(v:true) {$boost |}"
format_alt = " $icon $max_frequency.eng(w:3,hide_unit:true,hide_prefix:true) $barchart {$boost |}"
interval = 2

[[block]]
block = "temperature"
interval = 2
idle = 70
info = 80
warning = 90
format = " $icon "
format_alt = " $icon {$average}C "

[[block]]
block = "backlight"
step_width = 1
format = " $icon "
cycle = [0, 50, 100]
minimum = 0
missing_format = ""

[[block]]
block = "custom"
persistent = true
# TODO: why does this need a subshell?
command = 'dbus-monitor --system --profile "path=/net/hadess/PowerProfiles,member=PropertiesChanged" 2>/dev/null | xargs -I{} sh -c "powerprofilesctl get | sed \"s/per.*/󰓅/;s/bal.*/󰾅/;s/.*sav.*/󰾆/\""'
# TODO: rotate or show menu?
click = [
  { button = "left", cmd = "powerprofilesctl set performance" },
  { button = "middle", cmd = "powerprofilesctl set balanced" },
  { button = "right", cmd = "powerprofilesctl set power-saver" },
]

[[block]]
block = "notify"
driver = "dunst"

[[block]]
block = "sound"
step_width = 1
click = [
  { button = "left", cmd = "audio-select" },
  { button = "middle", cmd = "pavucontrol" },
]

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%-I:%M%P') "
interval = 2
click = [
  { button = "left", cmd = "notify-send -i calendar -a date $(date +%D)" },
]
