invert_scrolling = true

[icons]
icons = "awesome6"
[icons.overrides]
volume_muted = ""
cpu = ""
cpu_boost_on = "󱐋"
backlight = ["󰌶", "󱩎", "󱩏", "󱩐", "󱩑", "󱩒", "󱩓", "󱩔", "󱩕", "󱩖", "󰛨"]
bat = ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
bat_charging = ["󰢟", "󰢜", "󰂆", "󰂇", "󰂈", "󰢝", "󰂉", "󰢞", "󰂊", "󰂋", "󰂄"]
weather_clouds_night = ""

[theme]
theme = "ctp-mocha"
[theme.overrides]
separator = "|"
separator_fg = "#cdd6f4"
separator_bg = "#313244"

[[block]]
block = "music"
icons_format = " {icon} "
format = " $icon {$combo.str(max_w:35) $prev$play$next |}"

[[block]]
block = "weather"
format = " $icon $temp "
format_alt = " $icon $temp {({$temp_fmin}-{$temp_fmax}) |}"
autolocate = true
autolocate_interval = "once"
service = { name = "openweathermap", units = "imperial", forecast_hours = 24 }

[[block]]
block = "memory"
format = " $icon $mem_used_percents.bar(v:true) "
format_alt = " $icon_swap $swap_used_percents.bar(v:true) "

[[block]]
block = "cpu"
format = " $icon $utilization.bar(v:true) {$boost |}"
format_alt = " $icon $max_frequency.eng(w:3,hide_unit:true,hide_prefix:true) $barchart {$boost |}"
interval = 2

[[block]]
block = "temperature"
interval = 2
idle = 70
info = 80
warning = 90
format = " $icon "
format_alt = " $icon {$average}C "

[[block]]
block = "backlight"
step_width = 1
format = " $icon "
cycle = [0, 50, 100]
minimum = 0
missing_format = ""

[[block]]
block = "battery"
format = " $icon $power "
interval = 5
missing_format = ""

[[block]]
block = "notify"
driver = "swaync"

[[block]]
block = "sound"
step_width = 1
click = [
  { button = "left", cmd = "audio-select" },
  { button = "middle", cmd = "pavucontrol" },
]

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%-I:%M%P') "
interval = 2
click = [
  { button = "left", cmd = "notify-send -i calendar -a date $(date +%D)" },
]
