[icons]
icons = "awesome5"
[icons.overrides]
volume_muted = "\uf466"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = "|"
separator_fg = "#aaaaaa"
separator_bg = "#282828"

[[block]]
block = "music"
icons_format = " {icon} "
format = " $icon $title.str(max_w:35) $prev$play$next"
theme_overrides = { "info_bg" = "#282828" }

[[block]]
block = "notify"

[[block]]
block = "sound"
step_width = 1
click = [{ button = "left", cmd = "pavucontrol" }]

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%-I:%M%P') "
interval = 3
click = [{ button = "left", cmd = "notify-send -i calendar -a date $(date +%D)" }]
