invert_scrolling = true

[icons]
icons = "awesome5"
[icons.overrides]
volume_muted = "\uf466"
cpu = "\uf0e4"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = "|"
separator_fg = "#aaaaaa"
separator_bg = "#282828"

[[block]]
block = "music"
icons_format = " {icon} "
format = " $icon {$combo.str(max_w:35) $prev$play$next |}"
theme_overrides = { "info_bg" = "#282828" }

[[block]]
block = "weather"
format = " $icon {$temp}F "
autolocate = true
autolocate_interval = "once"
service = { name = "openweathermap", units = "imperial" }

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon_swap $swap_used_percents "

[[block]]
block = "cpu"
format = " $icon $utilization "
interval = 3

[[block]]
block = "temperature"
interval = 3
idle = 50
info = 70
format = " $icon {$average}C "

[[block]]
block = "backlight"
step_width = 1
invert_icons = true

[[block]]
block = "battery"

[[block]]
block = "notify"
driver = "swaync"

[[block]]
block = "sound"
step_width = 1
click = [{ cmd = "pkill -f pavucontrol || pavucontrol &", button = "left" }]

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%-I:%M%P') "
interval = 3
click = [{ button = "left", cmd = "notify-send $(date +%D)" }]
