invert_scrolling = true

[icons]
icons = "awesome6"
[icons.overrides]
volume_muted = "\uf466"
cpu = "\uf0e4"

[theme]
theme = "ctp-mocha"
[theme.overrides]
separator = "|"
separator_fg = "#cdd6f4"
separator_bg = "#313244"

[[block]]
block = "music"
icons_format = " {icon} "
format = " $icon {$combo.str(max_w:35) $prev$play$next |}"

[[block]]
block = "weather"
format = " $icon $temp "
format_alt = " $icon_ffin $temp {({$temp_fmin}-{$temp_fmax}) |}"
autolocate = true
autolocate_interval = "once"
service = { name = "openweathermap", units = "imperial", forecast_hours = 24 }

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon_swap $swap_used_percents "

[[block]]
block = "cpu"
format = " $icon{ $boost|} "
format_alt = " $icon$utilization{ $boost|} "
interval = 3

[[block]]
block = "temperature"
interval = 3
idle = 70
info = 80
warning = 90
format = " $icon "
format_alt = " $icon {$average}C "

[[block]]
block = "backlight"
step_width = 1
invert_icons = true

[[block]]
block = "battery"

[[block]]
block = "notify"
driver = "swaync"

[[block]]
block = "sound"
step_width = 1
click = [{ button = "left", cmd = "audio-select" }]

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%-I:%M%P') "
interval = 3
click = [{ button = "left", cmd = "notify-send -i calendar -a date $(date +%D)" }]
